dependencies:
  #-<organization/repo name>@<version>
  - smartcontractkit/chainlink-brownie-contracts@0.3.0

compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.3.0'

dotenv: .env

wallets:
  from_key: ${PRIVATE_KEY}

networks:
  rinkeby:
    eth_usd_price_feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'
    verify: True
  ganache-local:
    verify: False
  development:
    verify: False